2. wordlist page
IlyaKhokhanov/dictionary_and_test pull request #2
Opened 2023-02-20 08:27 UTC by IlyaKhokhanov

2023-02-21 06:21 UTC, jahglow commented
rebase this on the first branch for now so that there are no file or commits from the first branch (this one should say merge into 1-homepage, not into main)

2023-02-21 07:09 UTC, jahglow requested changes
you need to know data structures well. There are multiple ways to achieve the result but this result might be slow as hell and glitchy and the app will be slow because of it and it's not React's fault)

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +  const [wordEye, setWordEye] = useState(false);
wordsVisible? think about purpose, not how it looks

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +              onClick={() => setWordEye(!wordEye)}>
this should be memoized in a callback. Setter can be passed  a function to avoid external dependencies, RTM (read the manual) on why `setWordsVisible(prevValue=>!prevValue)`

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +                alt='eye'
this alt text is bad, it is not descriptive to screen readers what pressing ершу button does.

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +            <button
make sure your button is at least 40-48 pixels square, otherwise it's hard to tap when on mobile devices

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +            <button
sounds like it has to be a reusable component, read on  DRY approach

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.scss
> +      padding: 0 5px;
style duplication as well, speaker and eye buttons have the same pattern, bmaybe make an IconButton with styles?

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +    webSpeech(e.target.closest(".table-cell").textContent);
really, pass a word to speak rather than find it in the dom...

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +  const data = Object.entries(db);
do it outside

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +  const memoData = useMemo(() => filterData(state, data), [state, data]);
filteredWords maybe?

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +        <tr key={word.word} className='table-row'>
word.word is baaaaad. think of another name for parent object

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +          <td className={`table-cell ${wordEye ? "hide" : ""}`}>
hidden instead of hide, think of states in classNames, not actions. actions are in functions

2023-02-21 07:09 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +                alt='eye'
you see the copy-pasting? Alt text should have meaning, reuse the IconButton here as well

2023-02-21 07:09 UTC, jahglow commented on src/utils/other.js
> +export const correctWord = (str) => str.charAt(0).toUpperCase() + str.slice(1);
a wrong name for the function. What does it do? Capitalise? then call it capitaliseWord, because `correct` about correction

2023-02-21 07:09 UTC, jahglow commented on src/utils/webSpeech.js
> +export default function webSpeech(value) {
speakWord?

2023-02-21 07:09 UTC, jahglow commented on src/utils/filterData.js
> +            arrModData.forEach((item) => res.push(item));
until here there are 5 nested cycles. This is hell. Read about data structures and reduce the number of cycles necessary to perform the task. use nested cycles only when it's inevitable. but usually it's never more that one inside another

2023-02-21 07:09 UTC, jahglow commented on src/utils/filterData.js
> +            arrModData.forEach((item) => res.push(item));
usually when you need to index something, you create a hashmap. JS has some data structures for that. Conform data outside of a cycle to reduce the time to find the necessary thing.
Try to avoid using forEach, reduce etc, because they are helpers but they are twice as slow as for() loop.

2023-02-21 07:09 UTC, jahglow commented on src/utils/filterData.js
> +          Object.entries(arrModulesData).forEach(([module, arrModData]) => {
object entries already makes you iterate over the whole object and then you iterate over it again with forEach. That's a waste of time inside a cycle already. there's a `for...in` for that

2023-02-21 07:09 UTC, jahglow commented on src/components/buttons/Button.scss
> +    background: rgb(50, 50, 50);
looks like you just have random hardcoded colors, fontsizes, what do you use scss for? nesting? What about variables?

2023-03-20 07:31 UTC, jahglow approved these changes
поправь и вливай

2023-03-20 07:31 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +              handler={() => setWordsVisible((prevValue) => !prevValue)}
callback

2023-03-20 07:31 UTC, jahglow commented on src/components/WordlistTable/WordlistTable.js
> +              handler={() => setTranslateVisible((prevValue) => !prevValue)}
and here

2023-03-20 07:31 UTC, jahglow commented on src/components/WordlistTableRow/WordlistTableRow.js
> +  const speakHandler = (e) => {
make it outside component, it's a statiс function not dependent on internals

2023-03-20 07:31 UTC, jahglow commented on src/components/buttons/IconButton/IconButton.js
> +        name={prop.spokenWord ? prop.spokenWord : ""}
```suggestion
        name={prop.spokenWord ?? ""}
```

2023-03-20 07:31 UTC, jahglow commented on src/utils/filterWords.js
> +  const objState = Object.fromEntries(state);
а почему не итерировать по массиву state¿ зачем из них создавать объект чтобы итерировать по объекту?

2023-03-20 07:31 UTC, jahglow commented on src/utils/formUtils/formUtils.js
> +    seter(data);
зря ты так) верни

2023-04-14 19:27 UTC, IlyaKhokhanov commented on src/utils/filterWords.js
> +  const objState = Object.fromEntries(state);
здесь state - это коллекция Map, удобнее просто в объект преобразовать, просто до этого по объекту проходился

2023-04-14 21:44 UTC, IlyaKhokhanov commented on src/utils/filterWords.js
> +  const objState = Object.fromEntries(state);
переделал на итерацию по массиву

2023-04-17 09:47 UTC, merged