1. start page
IlyaKhokhanov/dictionary_and_test pull request #4
Opened 2023-02-20 11:24 UTC by IlyaKhokhanov

- Make start page
- Take data from data.json and show this data in checkboxes
- Saving data from checkbox with useReducer and give this data to other pages with useContext

2023-02-20 16:37 UTC, jahglow requested changes
В общем есть что испраить тут. обрати внимание на создание непримитивов внутри компонентов - оборачивай такое в useMemo чтобы избежаь ненужных ререндеров. Как поправишь всё - еще раз тегни меня.

2023-02-20 16:37 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +export default function CheckboxModule(props) {
старайся не использовать default export нигде кроме мест где это необходимо (для `lazy(()=>import(./default/export/modue.js))`)

2023-02-20 16:37 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +  const listModules = Object.keys(modules);
тут при каждом рендере ты создаешь массив с ключами, мемоизируй, чтобы избежать перерисовки

2023-02-20 16:37 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +            onChange={(e) => dispatch(e)}
если диспатч имеет один в один аргумент, зачем ты пихаешь его вызов в анонимную функцию которая на каждый чих будет пересоздаваться и вызывать частый garbage collection (GC)? просто передай саму функцию dispatch в onClick. Но что-то мне подсказывает ты неверно используешь dispatch? потому что он наверное не то ожидает что ты в него сунул

2023-02-20 16:37 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +  const { dispatch } = useContext(CheckboxContext);
у тебя контекст может быть теоретически неопределен, потмоу что в его инициализации нет ничего, а тут ты его деструктурируешь уже и у тебя будет runtime error

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +import CheckboxModule from "../CheckboxModule/CheckboxModule";
чувствуешь тебе не хватает index.js который бы делал реэкспорт CheckboxModule (export * from './CheckboxModule') и тогда бы импорт выглядел нормально (без повторений)

2023-02-20 16:37 UTC, jahglow commented on src/state/CheckboxContext.js
> +export const CheckboxContext = createContext();
ужасно название, оно не гвоорит ничего о том, что там лежит, оно гворит о принадлежности чекбоксам. подумай как его лучше переименовать и отрефакторить, чтобы оно было более очевидным о содержимом или назначении

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +    <form className='form' onSubmit={(e) => e.preventDefault()}>
зачем ты все обернул в форму, в которой нет ни одного сабмита? поля могут и без формы жить

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +  const data = Object.entries(db);
это надо вне компонента объявлять, зачем каждый рендер делать то, что не зависит от пропсов компонента?

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +              checked={state.find((item) => item.schoolbook === key)}
плохая идея в цикле гонять еще find? подумай какую структуру данных лучше использовать для сложность O(1) и в каком виде хранить данные

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +              onChange={(e) => dispatch(e)}
просто dispatch

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +          {state.find((item) => item.schoolbook === key) && (
еще один цикл. может внутри цикла сделаешь константу "checked"? ты же дважды уже гоняешь по массиву умножить на количество учебников и количество рендеров (чеканье чекбокса, изменение state и всех пропсов) - то есть не меньше сотни раз

2023-02-20 16:37 UTC, jahglow commented on src/components/Form.js/Form.js
> +  const { state, dispatch } = useContext(CheckboxContext);
state - не описательное название переменной - не понятно что она тут делает и чтов ней хранится

2023-02-20 16:37 UTC, jahglow commented on src/components/Header/Header.js
> +  const { classForBtn, children } = props;
buttonClass?

2023-02-20 16:37 UTC, jahglow commented on src/components/Header/Header.js
> +import "./Header.scss";
может включить buttonclass в этот файл чтобы не таскать его везде через пропсы или он меняется?

2023-02-20 16:37 UTC, jahglow commented on src/components/buttons/Button.js
> +    <Link className={`btn ${classForBtn}`} to={to || "/"}>
используй `??` вместо `||` для `null | undefined `

2023-02-20 16:37 UTC, jahglow commented on src/data/data.json
> +        "id": 10,
тебе тут точно нужен id или индекса хватит внутри массива?

2023-02-20 16:37 UTC, jahglow commented on src/data/data.json
> +  "Schoolbook 2": {
по спеку надо было учебники хранить в разных json, потому что они должны были подгружаться только по требованию

2023-02-20 16:37 UTC, jahglow commented on src/state/FormReducer.js
> +  console.log(state);
лишний лог?

2023-02-20 16:37 UTC, jahglow commented on src/state/FormReducer.js
> +    const getSchoolbook = e.target.closest("[data-schoolbook]");
так себе идея гонять по дом дереву вне реакта и что-то там искать, как будто у тебя на руках данных нет

2023-02-20 16:37 UTC, jahglow commented on src/state/FormReducer.js
> +      state[indexSchoolbook].modules.push(e.target.id);
ты на самом деле тут по жесткому мутируешь стейт и думаешь что он у тебя иммутабельный. лучше используй immer

2023-02-20 16:37 UTC, jahglow commented on src/state/FormReducer.js
> +      state[indexSchoolbook].modules.splice(indexModule, 1);
и тут

2023-02-20 16:37 UTC, jahglow commented on src/state/FormReducer.js
> +export default function FormReducer(state, e) {
подумай как организовать лучше эту функцию, нужен ли тебе на самом деле редьюсер, может разобьёшь ее внутренности на отдельные функции чтобы было понятно и не простыня кода. Ну и избавься от поиска по дереву нод

2023-02-20 16:37 UTC, jahglow commented on src/state/FormReducer.js
> +export default function FormReducer(state, e) {
по конвенции не должно быть название функции с большой буквы если жто не класс и не компонент. camelCase. ну и дефолтный экспорт опять

2023-02-28 09:54 UTC, jahglow commented
так, на гитхаб страницы должно деплоиться само работающее приложение а не readme)

2023-02-28 10:35 UTC, jahglow requested changes

2023-02-28 10:35 UTC, jahglow commented on public/index.html
> -      content="Web site created using create-react-app"
плохой дескрипшен не отражающий сути сайта

2023-02-28 10:35 UTC, jahglow commented on src/App.js
>        value={{
в будущем не передавай в провайдер динамически создаваемый объект, он будет заставлять там всё перерендериваться даже если ничего не поменялось, потомоу что просто создается новый объект

2023-02-28 10:35 UTC, jahglow commented on src/App.js
> +    <selectedModulesContext.Provider
название контекста всегда с большой буквы пишется

2023-02-28 10:35 UTC, jahglow commented on public/data/Schoolbook 1.json
> +{
наверное эти файлы не должны трекаться в git? они же автогенерятся? добавь папку в исключения если да

2023-02-28 10:35 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +export default function CheckboxModule(props) {
так и не поменял

2023-02-28 10:35 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +  const { checkedModules, setCheckedModules } = useContext(
здесь тайпскрипт тебе выкинет в будущем исключение, потомоу что у тебя создается пустой контекст (undefined) а теперь ты пытаешься потенциальный undefined деструктурировать как обект

2023-02-28 10:35 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +  const { checkedModules, setCheckedModules } = useContext(
я обычно использую такой кастомный хук (типы можешь убрать пока):
```ts
import { Context, useContext } from 'react';

export function useRequiredContext<T>(context: Context<T | undefined>, errorMessage?: string): T {
  const result = useContext(context);

  if (result === undefined) {
    throw new Error(
      errorMessage ?? `Required context ${context.displayName ? `${context.displayName} ` : ''}is not present.`,
    );
  }

  return result;
}
```
тогда моешь смело из него деструктурировать подменив в своем коде useContext на useRequiredContext

2023-02-28 10:35 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +        produce((draft) => {
а где первый аргумент produce? 
```setCheckedModules(prevModules=>produce(prevModules, draft=>{...}))```

2023-02-28 10:35 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +      setCheckedModules(
тебе не кажется, что лучше не повторяться и оба условия выполнить внутри setCheckedModules() и его produce?

2023-02-28 10:35 UTC, jahglow commented on src/utils/formUtils/formUtils.js
> +export async function fetchJsonModules(schoolbook, seter) {
setter

2023-02-28 10:35 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +  function modulesCheckboxHandler(e) {
не мемоизировал колбек

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +const CheckboxModule = lazy(() => import("../CheckboxModule/CheckboxModule"));
а зачем ты тут его лениво тащишь? Это же первая страница, на которой у тебя обязательно будут модули. Тебе не надо так делать. тебе надо написать скрипт nodejs который ты будешь выполнять как build step команду - перед билдом приложения в деве или проде - она будет пробегать по всем файлам из data и генерить файл с нужными тебе данными, например ключи и названия всех учебников, список модулей в учебнике. - это все кидается в какой-нибудь создаваемый generated.js или json и именно его ты статически импортируешь. там же у тебя должны подставляться функции динамического импорта нужных тебе json файлов (иначе у тебя вебпак не соберет их как чанки при продакшен билде). Этот файл избавит тебя от ручного ведения модулей, когда ты добавишь новый учебник или раздел. используй для этого библиотеку loadable например.

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +const CheckboxModule = lazy(() => import("../CheckboxModule/CheckboxModule"));
исполнение nodejs скрипта в консоли или package.json scripts делается так: `node src/scripts/generateModuleLinks.js`

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +    () => renderCheckboxSchoolbooks(totalSchoolbooks),
вводящее. взаблуждение название функции - тут нет никакого рендера.

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +    setCheckedModules({
ты проверял что это работает? мне кажется ты ввел себя в заблуждение - ты создаешь обект в котором спредишь еще один объект у которого ключ id чекбокса а значение пустой массив. При вызове хенждлера сколько бы ты чекбоксов не жмакнул у тебя будет происходить одно и то же действие а не добавление нового к тому что было. используй функцию в сеттере и спредь первый аргументб второй спред не нужен на следующейй строке, просто обявляй динамический ключ. Оберни в useCallback всякую функцию которую ты используешь в рендере

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +      {!!Object.keys(checkedModules).length && (
на каждый чих создание массива ключей с прогоном по объекту. это точно нельзя мемоизировать?)

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +      {!!Object.keys(checkedModules).length && (
а если тебе тут надо только длина, может использовать Map() у которого есть size?

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +      {!!Object.keys(checkedModules).length && (
пjможет тебе использовать ключ на 36 строке `checkedModules.has(schoolbook)`/ Кстати schoolbook - это прямо учебник или строка? может id? так можт отразишь в названии что это? Обязательно возми в качестве чтения на ночь вот эту книгу: https://vk.com/wall-54530371_90838

2023-02-28 10:35 UTC, jahglow commented on src/components/Header/Header.js
> +import "./Header.scss";
почему не импортируешь css для стиля кнопки а получаешь через хедер? она меняется? разные классы принимает?

2023-02-28 10:35 UTC, jahglow commented on src/components/Form/Form.js
> +  const totalSchoolbooks = 2;
вот пример плохого хардкода - это ты как раз должен брать из сгенеренного файла

2023-03-01 11:01 UTC, IlyaKhokhanov commented on src/components/CheckboxModule/CheckboxModule.js
> +export default function CheckboxModule(props) {
здесь не поменял, потому что через lazy подгружаю, в остальных местах поменял

2023-03-01 11:11 UTC, IlyaKhokhanov commented on src/data/data.json
> +        "id": 10,
пока оставил, возможно не понадобится

2023-03-02 12:22 UTC, IlyaKhokhanov commented on src/components/Header/Header.js
> +import "./Header.scss";
- стили кнопки меняются:
1. в компоненте Form, докидываю отступ
2. на страницах через пропсы компонента Header прокидываю стили, допустим в Home display: none
- в Header не надо импортировать стили кнопки, они в компоненте Button импортируются

2023-03-03 13:00 UTC, jahglow approved these changes
поправь и вливай

2023-03-03 13:00 UTC, jahglow commented on public/index.html
> +      content="Applicatio with Russian dictionary and tests" />
typo

2023-03-03 13:00 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +          !prevModules.get(schoolbook).includes(e.target.id)
либо ты делаешь не тернарник (его плохо читать) либо ты его преносишь вторым аргументом для draft.set чтобы избежать повторения

2023-03-03 13:00 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +            defaultChecked={checkedModules.get(schoolbook).includes(module)}
должно быть со знаком вопроса: `get(schoolbook)?.includes` - сам скажи мне почему))

2023-03-03 13:00 UTC, jahglow commented on src/components/CheckboxModule/CheckboxModule.js
> +            defaultChecked={checkedModules.get(schoolbook).includes(module)}
и по этой причине оберни это выражение в Boolean или поставь `!!`перед ним

2023-03-03 13:00 UTC, jahglow commented on src/components/Form/Form.js
> +            draft.clear();
добавь сюда коммент что это дает и почему надо очищать

2023-03-03 22:14 UTC, merged